//This file is automatically generated by generator.lua from https://github.com/cimgui/cimguizmo
//based on ImGuizmo.h file version  1.61 WIP from https://github.com/CedricGuillemet/ImGuizmo
#ifndef CIMGUIZMOQUAT_INCLUDED
#define CIMGUIZMOQUAT_INCLUDED
#include <stdio.h>
#include <stdint.h>
#if defined _WIN32 || defined __CYGWIN__
    #ifdef CIMGUI_NO_EXPORT
        #define API
    #else
        #define API __declspec(dllexport)
    #endif
    #ifndef __GNUC__
    #define snprintf sprintf_s
    #endif
#else
    #ifdef __GNUC__
        #define API  __attribute__((__visibility__("default")))
    #else
        #define API
    #endif
#endif

#if defined __cplusplus
    #define EXTERN extern "C"
#else
    #include <stdarg.h>
    #include <stdbool.h>
    #define EXTERN extern
#endif

#define CIMGUI_API EXTERN API
#define CONST const


#ifdef _MSC_VER
typedef unsigned __int64 ImU64;
#else
//typedef unsigned long long ImU64;
#endif


#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS

typedef struct{
	float x,y,z,w;
}Vec4;

typedef struct{
	union {
		float f[16];
        Vec4 v[4];
        struct {      float m00, m01, m02, m03,
                        m10, m11, m12, m13,
                        m20, m21, m22, m23,
                        m30, m31, m32, m33; };
    };
}Mat4;

typedef struct{
	float x,y,z,w;
}quat;

typedef enum      {                            //0b0000'0000, //C++14 notation
                mode3Axes          = 0x01, //0b0000'0001, 
                modeDirection      = 0x02, //0b0000'0010,
                modeDirPlane       = 0x04, //0b0000'0010,
                modeDual           = 0x08, //0b0000'1000,
                modeMask           = 0x0f, //0b0000'1111,
                

                cubeAtOrigin       = 0x10, //0b0000'0000, 
                sphereAtOrigin     = 0x20, //0b0001'0000,
                noSolidAtOrigin    = 0x40, //0b0010'0000,
                modeFullAxes       = 0x80,
                axesModeMask       = 0xf0  //0b1111'0000
    } gizmo_modes;
	
#else
#endif // CIMGUI_DEFINE_ENUMS_AND_STRUCTS

#ifndef CIMGUI_DEFINE_ENUMS_AND_STRUCTS

#endif //CIMGUI_DEFINE_ENUMS_AND_STRUCTS

CIMGUI_API void resizeAxesOf(float sx,float sy, float sz);
CIMGUI_API void restoreAxesSize();
CIMGUI_API void setDirectionColor(const ImVec4 color);
CIMGUI_API void restoreDirectionColor();
CIMGUI_API void mat4_cast( quat *q,Mat4* mat);
/*
struct m16 {
    union {
        float v[16];
        struct {      float m00, m01, m02, m03,
                        m10, m11, m12, m13,
                        m20, m21, m22, m23,
                        m30, m31, m32, m33; };
    };
};
*/
//https://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/
CIMGUI_API void quat_cast(float f[16], quat *qq);
CIMGUI_API bool ImGuizmo3D(const char* label, quat *q, float size, const int mode);
CIMGUI_API bool ImGuizmo3Dquat(const char* label, float q[4], float size, const int mode);
CIMGUI_API bool ImGuizmo3Dvec4(const char* label, float a[4], float size, const int mode);
CIMGUI_API bool ImGuizmo3Dvec3(const char*label ,float v[3],float size,const int mode);
CIMGUI_API bool ImGuizmo3Dquatquat(const char*label,float q1[4],float q2[4],float size,const int mode);
CIMGUI_API bool ImGuizmo3Dquatvec4(const char* label,float q[4],float a[4],float size,const int mode);
CIMGUI_API bool ImGuizmo3Dquatvec3(const char* label, float q[4], float v[3],float size,const int mode);


#endif //CIMGUIZMOQUAT_INCLUDED




