//This file is automatically generated by generator.lua from https://github.com/cimgui/cimguizmo_quat
//based on imGuIZMOquat.h file version  XXX from https://github.com/BrutPitt/imGuIZMO.quat
#ifndef CIMGUIZMO_INCLUDED
#define CIMGUIZMO_INCLUDED

#include "cimgui.h"

#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS

typedef int vgButtons;
typedef int vgModifiers;

typedef struct Vec4{
	float x,y,z,w;
}Vec4;

typedef struct vec4{
	float x,y,z,w;
}vec4;

typedef struct vec3{
	float x,y,z;
}vec3;

typedef struct Mat4{
	union {
		float f[16];
        Vec4 v[4];
        /*struct {      float m00, m01, m02, m03,
                        m10, m11, m12, m13,
                        m20, m21, m22, m23,
                        m30, m31, m32, m33; };*/
    };
}Mat4;

typedef struct quat{
	float x,y,z,w;
}quat;



typedef struct ImVector_vec3 {int Size;int Capacity;vec3* Data;} ImVector_vec3;

typedef struct imguiGizmo imguiGizmo;
struct imguiGizmo
{
    quat qtV;
    quat qtV2;
    vec3 posPanDolly;
    vgButtons buttonPanDolly;
    vec3 axesVecModifier;
    int drawMode;
    int axesOriginType;
    bool showFullAxes;
};
    enum {
                mode3Axes = 0x0001,
                modeDirection = 0x0002,
                modeDirPlane = 0x0004,
                modeDual = 0x0008,
                modePanDolly = 0x0010,
                modeMask = 0x00ff,
                cubeAtOrigin = 0x0100,
                sphereAtOrigin = 0x0200,
                noSolidAtOrigin = 0x0400,
                modeFullAxes = 0x0800,
                axesModeMask = 0xff00
    };
    enum { sphereTess16, sphereTess8, sphereTess4, sphereTess2 };
    enum { CONE_SURF, CONE_CAP, CYL_SURF, CYL_CAP };
    enum { axisIsX, axisIsY, axisIsZ };
typedef enum { backSide, frontSide }solidSides;
#else
#endif // CIMGUI_DEFINE_ENUMS_AND_STRUCTS




#ifndef CIMGUI_DEFINE_ENUMS_AND_STRUCTS
typedef imguiGizmo::solidSides solidSides;
typedef ImVector<vec3> ImVector_vec3;
CIMGUI_API void imguiGizmo_buildPlane(const float size,const float thickness);
CIMGUI_API void imguiGizmo_buildCube(const float size);
CIMGUI_API void imguiGizmo_buildPolygon(const vec3 size,ImVector_vec3 * vtx,ImVector_vec3 * norm);
CIMGUI_API void imguiGizmo_buildSphere(float radius,int tessFactor);
CIMGUI_API void imguiGizmo_buildCone(float x0,float x1,float radius,int slices);
CIMGUI_API void imguiGizmo_buildCylinder(float x0,float x1,float radius,int slices);
CIMGUI_API void imguiGizmo_resizeAxesOf(const vec3 newSize);
CIMGUI_API void imguiGizmo_restoreAxesSize(void);
CIMGUI_API void imguiGizmo_resizeSolidOf(float newSize);
CIMGUI_API void imguiGizmo_restoreSolidSize(void);
CIMGUI_API void imguiGizmo_setDirectionColor_U32U32(ImU32 dColor,const ImU32 pColor);
CIMGUI_API void imguiGizmo_setDirectionColor_Vec4Vec4(const ImVec4_c dColor,const ImVec4_c pColor);
CIMGUI_API void imguiGizmo_setDirectionColor_U32(ImU32 color);
CIMGUI_API void imguiGizmo_setDirectionColor_Vec4(const ImVec4_c color);
CIMGUI_API void imguiGizmo_restoreDirectionColor(void);
CIMGUI_API void imguiGizmo_setSphereColors_Vec4(const ImVec4_c a,const ImVec4_c b);
CIMGUI_API void imguiGizmo_setSphereColors_U32(ImU32 a,ImU32 b);
CIMGUI_API void imguiGizmo_restoreSphereColors(void);
CIMGUI_API void imguiGizmo_setGizmoFeelingRot(float f);
CIMGUI_API float imguiGizmo_getGizmoFeelingRot(void);
CIMGUI_API void imguiGizmo_setPanModifier(vgModifiers v);
CIMGUI_API void imguiGizmo_setDollyModifier(vgModifiers v);
CIMGUI_API void imguiGizmo_setDollyScale(float scale);
CIMGUI_API float imguiGizmo_getDollyScale(void);
CIMGUI_API void imguiGizmo_setDollyWheelScale(float scale);
CIMGUI_API float imguiGizmo_getDollyWheelScale(void);
CIMGUI_API void imguiGizmo_setPanScale(float scale);
CIMGUI_API float imguiGizmo_getPanScale(void);
CIMGUI_API void imguiGizmo_flipRotOnX(bool b);
CIMGUI_API void imguiGizmo_flipRotOnY(bool b);
CIMGUI_API void imguiGizmo_flipRotOnZ(bool b);
CIMGUI_API void imguiGizmo_setFlipDolly(bool b);
CIMGUI_API void imguiGizmo_setFlipPanX(bool b);
CIMGUI_API void imguiGizmo_setFlipPanY(bool b);
CIMGUI_API bool imguiGizmo_getFlipRotOnX(void);
CIMGUI_API bool imguiGizmo_getFlipRotOnY(void);
CIMGUI_API bool imguiGizmo_getFlipRotOnZ(void);
CIMGUI_API bool imguiGizmo_getFlipPanX(void);
CIMGUI_API bool imguiGizmo_getFlipPanY(void);
CIMGUI_API bool imguiGizmo_getFlipDolly(void);
CIMGUI_API void imguiGizmo_reverseX(bool b);
CIMGUI_API void imguiGizmo_reverseY(bool b);
CIMGUI_API void imguiGizmo_reverseZ(bool b);
CIMGUI_API bool imguiGizmo_getReverseX(void);
CIMGUI_API bool imguiGizmo_getReverseY(void);
CIMGUI_API bool imguiGizmo_getReverseZ(void);
CIMGUI_API bool imguiGizmo_drawFunc(imguiGizmo* self,const char* label,float size);
CIMGUI_API void imguiGizmo_modeSettings(imguiGizmo* self,uint32_t mode);
CIMGUI_API void imguiGizmo_setDualMode(imguiGizmo* self,const uint32_t mode);
CIMGUI_API bool imguiGizmo_getTransforms_vec3Ptr(imguiGizmo* self,quat* q,const char* label,vec3* vDir,float size);
CIMGUI_API bool imguiGizmo_getTransforms_vec4Ptr(imguiGizmo* self,quat* q,const char* label,vec4* axis_angle,float size);
CIMGUI_API vec3 imguiGizmo_checkTowards_vec3(imguiGizmo* self,const vec3 v);
CIMGUI_API vec4 imguiGizmo_checkTowards_vec4(imguiGizmo* self,const vec4 v);
CIMGUI_API quat imguiGizmo_checkTowards_quat(imguiGizmo* self,const quat q);
CIMGUI_API bool iggizmo3D_quatPtrFloat(const char* t,quat* q,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec4Ptr(const char* t,vec4* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrFloat(const char* t,vec3* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_quatPtrquatPtr(const char* t,quat* q,quat* ql,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_quatPtrvec4Ptr(const char* t,quat* q,vec4* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_quatPtrvec3Ptr(const char* t,quat* q,vec3* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrFloat(const char* t,vec3* vm,quat* q,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3Ptrvec4Ptr(const char* t,vec3* vm,vec4* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3Ptrvec3Ptr(const char* t,vec3* vm,vec3* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrquatPtr(const char* t,vec3* vm,quat* q,quat* ql,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrvec4Ptr(const char* t,vec3* vm,quat* q,vec4* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrvec3Ptr(const char* t,vec3* vm,quat* q,vec3* v,float sz,uint32_t flag);
#endif //CIMGUI_DEFINE_ENUMS_AND_STRUCTS
#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS
CIMGUI_API void imguiGizmo_buildPlane(const float size,const float thickness);
CIMGUI_API void imguiGizmo_buildCube(const float size);
CIMGUI_API void imguiGizmo_buildPolygon(const vec3 size,ImVector_vec3 * vtx,ImVector_vec3 * norm);
CIMGUI_API void imguiGizmo_buildSphere(float radius,int tessFactor);
CIMGUI_API void imguiGizmo_buildCone(float x0,float x1,float radius,int slices);
CIMGUI_API void imguiGizmo_buildCylinder(float x0,float x1,float radius,int slices);
CIMGUI_API void imguiGizmo_resizeAxesOf(const vec3 newSize);
CIMGUI_API void imguiGizmo_restoreAxesSize(void);
CIMGUI_API void imguiGizmo_resizeSolidOf(float newSize);
CIMGUI_API void imguiGizmo_restoreSolidSize(void);
CIMGUI_API void imguiGizmo_setDirectionColor_U32U32(ImU32 dColor,const ImU32 pColor);
CIMGUI_API void imguiGizmo_setDirectionColor_Vec4Vec4(const ImVec4_c dColor,const ImVec4_c pColor);
CIMGUI_API void imguiGizmo_setDirectionColor_U32(ImU32 color);
CIMGUI_API void imguiGizmo_setDirectionColor_Vec4(const ImVec4_c color);
CIMGUI_API void imguiGizmo_restoreDirectionColor(void);
CIMGUI_API void imguiGizmo_setSphereColors_Vec4(const ImVec4_c a,const ImVec4_c b);
CIMGUI_API void imguiGizmo_setSphereColors_U32(ImU32 a,ImU32 b);
CIMGUI_API void imguiGizmo_restoreSphereColors(void);
CIMGUI_API void imguiGizmo_setGizmoFeelingRot(float f);
CIMGUI_API float imguiGizmo_getGizmoFeelingRot(void);
CIMGUI_API void imguiGizmo_setPanModifier(vgModifiers v);
CIMGUI_API void imguiGizmo_setDollyModifier(vgModifiers v);
CIMGUI_API void imguiGizmo_setDollyScale(float scale);
CIMGUI_API float imguiGizmo_getDollyScale(void);
CIMGUI_API void imguiGizmo_setDollyWheelScale(float scale);
CIMGUI_API float imguiGizmo_getDollyWheelScale(void);
CIMGUI_API void imguiGizmo_setPanScale(float scale);
CIMGUI_API float imguiGizmo_getPanScale(void);
CIMGUI_API void imguiGizmo_flipRotOnX(bool b);
CIMGUI_API void imguiGizmo_flipRotOnY(bool b);
CIMGUI_API void imguiGizmo_flipRotOnZ(bool b);
CIMGUI_API void imguiGizmo_setFlipDolly(bool b);
CIMGUI_API void imguiGizmo_setFlipPanX(bool b);
CIMGUI_API void imguiGizmo_setFlipPanY(bool b);
CIMGUI_API bool imguiGizmo_getFlipRotOnX(void);
CIMGUI_API bool imguiGizmo_getFlipRotOnY(void);
CIMGUI_API bool imguiGizmo_getFlipRotOnZ(void);
CIMGUI_API bool imguiGizmo_getFlipPanX(void);
CIMGUI_API bool imguiGizmo_getFlipPanY(void);
CIMGUI_API bool imguiGizmo_getFlipDolly(void);
CIMGUI_API void imguiGizmo_reverseX(bool b);
CIMGUI_API void imguiGizmo_reverseY(bool b);
CIMGUI_API void imguiGizmo_reverseZ(bool b);
CIMGUI_API bool imguiGizmo_getReverseX(void);
CIMGUI_API bool imguiGizmo_getReverseY(void);
CIMGUI_API bool imguiGizmo_getReverseZ(void);
CIMGUI_API bool imguiGizmo_drawFunc(imguiGizmo* self,const char* label,float size);
CIMGUI_API void imguiGizmo_modeSettings(imguiGizmo* self,uint32_t mode);
CIMGUI_API void imguiGizmo_setDualMode(imguiGizmo* self,const uint32_t mode);
CIMGUI_API bool imguiGizmo_getTransforms_vec3Ptr(imguiGizmo* self,quat* q,const char* label,vec3* vDir,float size);
CIMGUI_API bool imguiGizmo_getTransforms_vec4Ptr(imguiGizmo* self,quat* q,const char* label,vec4* axis_angle,float size);
CIMGUI_API vec3 imguiGizmo_checkTowards_vec3(imguiGizmo* self,const vec3 v);
CIMGUI_API vec4 imguiGizmo_checkTowards_vec4(imguiGizmo* self,const vec4 v);
CIMGUI_API quat imguiGizmo_checkTowards_quat(imguiGizmo* self,const quat q);
CIMGUI_API bool iggizmo3D_quatPtrFloat(const char* t,quat* q,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec4Ptr(const char* t,vec4* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrFloat(const char* t,vec3* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_quatPtrquatPtr(const char* t,quat* q,quat* ql,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_quatPtrvec4Ptr(const char* t,quat* q,vec4* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_quatPtrvec3Ptr(const char* t,quat* q,vec3* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrFloat(const char* t,vec3* vm,quat* q,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3Ptrvec4Ptr(const char* t,vec3* vm,vec4* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3Ptrvec3Ptr(const char* t,vec3* vm,vec3* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrquatPtr(const char* t,vec3* vm,quat* q,quat* ql,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrvec4Ptr(const char* t,vec3* vm,quat* q,vec4* v,float sz,uint32_t flag);
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrvec3Ptr(const char* t,vec3* vm,quat* q,vec3* v,float sz,uint32_t flag);
#endif //CIMGUI_DEFINE_ENUMS_AND_STRUCTS


#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS
CIMGUI_API void mat4_cast( quat *q,Mat4* mat);
CIMGUI_API void mat4_pos_cast( quat *q, vec3 pos, Mat4* mat);
CIMGUI_API void quat_cast(float f[16], quat *qq);
CIMGUI_API void quat_pos_cast(float f[16], quat *qq, vec3 *pos);
#else
CIMGUI_API void mat4_cast( quat *q,Mat4* mat);
CIMGUI_API void mat4_pos_cast( quat *q, vec3 pos, Mat4* mat);
CIMGUI_API void quat_cast(float f[16], quat *qq);
CIMGUI_API void quat_pos_cast(float f[16], quat *qq, vec3 *pos);
#endif

#endif //CIMGUIZMO_INCLUDED
