//This file is automatically generated by generator.lua from https://github.com/cimgui/cimguizmo_quat
//based on imGuIZMOquat.h file version  XXX from https://github.com/BrutPitt/imGuIZMO.quat
#include "imgui.h"
#include "imgui_internal.h"
#include "imGuIZMOquat.h"
#include "cimguizmo_quat.h"



CIMGUI_API void imguiGizmo_buildPlane(const float size,const float thickness)
{
    return imguiGizmo::buildPlane(size,thickness);
}
CIMGUI_API void imguiGizmo_buildCube(const float size)
{
    return imguiGizmo::buildCube(size);
}
CIMGUI_API void imguiGizmo_buildPolygon(const vec3 size,ImVector_vec3 * vtx,ImVector_vec3 * norm)
{
    return imguiGizmo::buildPolygon(size,*vtx,*norm);
}
CIMGUI_API void imguiGizmo_buildSphere(float radius,int tessFactor)
{
    return imguiGizmo::buildSphere(radius,tessFactor);
}
CIMGUI_API void imguiGizmo_buildCone(float x0,float x1,float radius,int slices)
{
    return imguiGizmo::buildCone(x0,x1,radius,slices);
}
CIMGUI_API void imguiGizmo_buildCylinder(float x0,float x1,float radius,int slices)
{
    return imguiGizmo::buildCylinder(x0,x1,radius,slices);
}
CIMGUI_API void imguiGizmo_resizeAxesOf(const vec3 newSize)
{
    return imguiGizmo::resizeAxesOf(newSize);
}
CIMGUI_API void imguiGizmo_restoreAxesSize()
{
    return imguiGizmo::restoreAxesSize();
}
CIMGUI_API void imguiGizmo_resizeSolidOf(float newSize)
{
    return imguiGizmo::resizeSolidOf(newSize);
}
CIMGUI_API void imguiGizmo_restoreSolidSize()
{
    return imguiGizmo::restoreSolidSize();
}
CIMGUI_API void imguiGizmo_setDirectionColor_U32U32(ImU32 dColor,const ImU32 pColor)
{
    return imguiGizmo::setDirectionColor(dColor,pColor);
}
CIMGUI_API void imguiGizmo_setDirectionColor_Vec4Vec4(const ImVec4 dColor,const ImVec4 pColor)
{
    return imguiGizmo::setDirectionColor(dColor,pColor);
}
CIMGUI_API void imguiGizmo_setDirectionColor_U32(ImU32 color)
{
    return imguiGizmo::setDirectionColor(color);
}
CIMGUI_API void imguiGizmo_setDirectionColor_Vec4(const ImVec4 color)
{
    return imguiGizmo::setDirectionColor(color);
}
CIMGUI_API void imguiGizmo_restoreDirectionColor()
{
    return imguiGizmo::restoreDirectionColor();
}
CIMGUI_API void imguiGizmo_setSphereColors_Vec4(const ImVec4 a,const ImVec4 b)
{
    return imguiGizmo::setSphereColors(a,b);
}
CIMGUI_API void imguiGizmo_setSphereColors_U32(ImU32 a,ImU32 b)
{
    return imguiGizmo::setSphereColors(a,b);
}
CIMGUI_API void imguiGizmo_restoreSphereColors()
{
    return imguiGizmo::restoreSphereColors();
}
CIMGUI_API void imguiGizmo_setGizmoFeelingRot(float f)
{
    return imguiGizmo::setGizmoFeelingRot(f);
}
CIMGUI_API float imguiGizmo_getGizmoFeelingRot()
{
    return imguiGizmo::getGizmoFeelingRot();
}
CIMGUI_API void imguiGizmo_setPanModifier(vgModifiers v)
{
    return imguiGizmo::setPanModifier(v);
}
CIMGUI_API void imguiGizmo_setDollyModifier(vgModifiers v)
{
    return imguiGizmo::setDollyModifier(v);
}
CIMGUI_API void imguiGizmo_setDollyScale(float scale)
{
    return imguiGizmo::setDollyScale(scale);
}
CIMGUI_API float imguiGizmo_getDollyScale()
{
    return imguiGizmo::getDollyScale();
}
CIMGUI_API void imguiGizmo_setDollyWheelScale(float scale)
{
    return imguiGizmo::setDollyWheelScale(scale);
}
CIMGUI_API float imguiGizmo_getDollyWheelScale()
{
    return imguiGizmo::getDollyWheelScale();
}
CIMGUI_API void imguiGizmo_setPanScale(float scale)
{
    return imguiGizmo::setPanScale(scale);
}
CIMGUI_API float imguiGizmo_getPanScale()
{
    return imguiGizmo::getPanScale();
}
CIMGUI_API void imguiGizmo_flipRotOnX(bool b)
{
    return imguiGizmo::flipRotOnX(b);
}
CIMGUI_API void imguiGizmo_flipRotOnY(bool b)
{
    return imguiGizmo::flipRotOnY(b);
}
CIMGUI_API void imguiGizmo_flipRotOnZ(bool b)
{
    return imguiGizmo::flipRotOnZ(b);
}
CIMGUI_API void imguiGizmo_setFlipDolly(bool b)
{
    return imguiGizmo::setFlipDolly(b);
}
CIMGUI_API void imguiGizmo_setFlipPanX(bool b)
{
    return imguiGizmo::setFlipPanX(b);
}
CIMGUI_API void imguiGizmo_setFlipPanY(bool b)
{
    return imguiGizmo::setFlipPanY(b);
}
CIMGUI_API bool imguiGizmo_getFlipRotOnX()
{
    return imguiGizmo::getFlipRotOnX();
}
CIMGUI_API bool imguiGizmo_getFlipRotOnY()
{
    return imguiGizmo::getFlipRotOnY();
}
CIMGUI_API bool imguiGizmo_getFlipRotOnZ()
{
    return imguiGizmo::getFlipRotOnZ();
}
CIMGUI_API bool imguiGizmo_getFlipPanX()
{
    return imguiGizmo::getFlipPanX();
}
CIMGUI_API bool imguiGizmo_getFlipPanY()
{
    return imguiGizmo::getFlipPanY();
}
CIMGUI_API bool imguiGizmo_getFlipDolly()
{
    return imguiGizmo::getFlipDolly();
}
CIMGUI_API void imguiGizmo_reverseX(bool b)
{
    return imguiGizmo::reverseX(b);
}
CIMGUI_API void imguiGizmo_reverseY(bool b)
{
    return imguiGizmo::reverseY(b);
}
CIMGUI_API void imguiGizmo_reverseZ(bool b)
{
    return imguiGizmo::reverseZ(b);
}
CIMGUI_API bool imguiGizmo_getReverseX()
{
    return imguiGizmo::getReverseX();
}
CIMGUI_API bool imguiGizmo_getReverseY()
{
    return imguiGizmo::getReverseY();
}
CIMGUI_API bool imguiGizmo_getReverseZ()
{
    return imguiGizmo::getReverseZ();
}
CIMGUI_API bool imguiGizmo_drawFunc(imguiGizmo* self,const char* label,float size)
{
    return self->drawFunc(label,size);
}
CIMGUI_API void imguiGizmo_modeSettings(imguiGizmo* self,uint32_t mode)
{
    return self->modeSettings(mode);
}
CIMGUI_API void imguiGizmo_setDualMode(imguiGizmo* self,const uint32_t mode)
{
    return self->setDualMode(mode);
}
CIMGUI_API bool imguiGizmo_getTransforms_vec3Ptr(imguiGizmo* self,quat* q,const char* label,vec3* vDir,float size)
{
    return self->getTransforms(*q,label,*vDir,size);
}
CIMGUI_API bool imguiGizmo_getTransforms_vec4Ptr(imguiGizmo* self,quat* q,const char* label,vec4* axis_angle,float size)
{
    return self->getTransforms(*q,label,*axis_angle,size);
}
CIMGUI_API vec3 imguiGizmo_checkTowards_vec3(imguiGizmo* self,const vec3 v)
{
    return self->checkTowards(v);
}
CIMGUI_API vec4 imguiGizmo_checkTowards_vec4(imguiGizmo* self,const vec4 v)
{
    return self->checkTowards(v);
}
CIMGUI_API quat imguiGizmo_checkTowards_quat(imguiGizmo* self,const quat q)
{
    return self->checkTowards(q);
}
CIMGUI_API bool iggizmo3D_quatPtrFloat(const char* t,quat* q,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*q,sz,flag);
}
CIMGUI_API bool iggizmo3D_vec4Ptr(const char* t,vec4* v,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*v,sz,flag);
}
CIMGUI_API bool iggizmo3D_vec3PtrFloat(const char* t,vec3* v,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*v,sz,flag);
}
CIMGUI_API bool iggizmo3D_quatPtrquatPtr(const char* t,quat* q,quat* ql,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*q,*ql,sz,flag);
}
CIMGUI_API bool iggizmo3D_quatPtrvec4Ptr(const char* t,quat* q,vec4* v,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*q,*v,sz,flag);
}
CIMGUI_API bool iggizmo3D_quatPtrvec3Ptr(const char* t,quat* q,vec3* v,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*q,*v,sz,flag);
}
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrFloat(const char* t,vec3* vm,quat* q,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*vm,*q,sz,flag);
}
CIMGUI_API bool iggizmo3D_vec3Ptrvec4Ptr(const char* t,vec3* vm,vec4* v,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*vm,*v,sz,flag);
}
CIMGUI_API bool iggizmo3D_vec3Ptrvec3Ptr(const char* t,vec3* vm,vec3* v,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*vm,*v,sz,flag);
}
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrquatPtr(const char* t,vec3* vm,quat* q,quat* ql,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*vm,*q,*ql,sz,flag);
}
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrvec4Ptr(const char* t,vec3* vm,quat* q,vec4* v,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*vm,*q,*v,sz,flag);
}
CIMGUI_API bool iggizmo3D_vec3PtrquatPtrvec3Ptr(const char* t,vec3* vm,quat* q,vec3* v,float sz,uint32_t flag)
{
    return ImGui::gizmo3D(t,*vm,*q,*v,sz,flag);
}


CIMGUI_API void mat4_cast( quat *q,Mat4* mat)
{
	*mat = mat4_cast(*q);
}

CIMGUI_API void mat4_pos_cast( quat *q, vec3 pos, Mat4* mat)
{
	*mat = mat4_cast(*q);
	mat->m30 = pos.x;
	mat->m31 = pos.y;
	mat->m32 = pos.z;
}

struct m16 {
    union {
        float v[16];
        struct {      float m00, m10, m20, m30,
                        m01, m11, m21, m31,
                        m02, m12, m22, m32,
                        m03, m13, m23, m33; };
    };
};

//https://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/
CIMGUI_API void quat_cast(float f[16], quat *qq)
{
	m16 m = *(m16*)f;
	float qw, qx, qy, qz;
	float tr = m.m00 + m.m11 + m.m22;

	if (tr > 0) { 
	float S = sqrt(tr+1.0f) * 2.0f; // S=4*qw 
	qw = 0.25f * S;
	qx = (m.m21 - m.m12) / S;
	qy = (m.m02 - m.m20) / S; 
	qz = (m.m10 - m.m01) / S; 
	} else if ((m.m00 > m.m11)&&(m.m00 > m.m22)) { 
	float S = sqrt(1.0f + m.m00 - m.m11 - m.m22) * 2.0f; // S=4*qx 
	qw = (m.m21 - m.m12) / S;
	qx = 0.25f * S;
	qy = (m.m01 + m.m10) / S; 
	qz = (m.m02 + m.m20) / S; 
	} else if (m.m11 > m.m22) { 
	float S = sqrt(1.0f + m.m11 - m.m00 - m.m22) * 2.0f; // S=4*qy
	qw = (m.m02 - m.m20) / S;
	qx = (m.m01 + m.m10) / S; 
	qy = 0.25f * S;
	qz = (m.m12 + m.m21) / S; 
	} else { 
	float S = sqrt(1.0f + m.m22 - m.m00 - m.m11) * 2.0f; // S=4*qz
	qw = (m.m10 - m.m01) / S;
	qx = (m.m02 + m.m20) / S;
	qy = (m.m12 + m.m21) / S;
	qz = 0.25f * S;
	}
	*qq = quat(qw, qx, qy, qz);
}

CIMGUI_API void quat_pos_cast(float f[16], quat *qq, vec3 *pos)
{
	quat_cast(f,qq);
	pos->x = f[12];
	pos->y = f[13];
	pos->z = f[14];
}


